### Load in NumPy (remember to pip install numpy first)

In [1]:
#import numpy library
import numpy as np

### The Basics

In [2]:
#create 1D array
arr1 =np.array([1,2,3])
arr1

array([1, 2, 3])

In [3]:
#check type of created array
print(arr1.dtype)

int32


In [40]:
#Get elements' type
print(arr1[0].dtype,arr1[1].dtype,arr1[2].dtype)

int32 int32 int32


In [41]:
# Get  array Dimension
arr1.ndim

1

In [42]:
# create 1D array with different data type
arr2=np.array([1, 2.0, 'Mohammed'])
arr2

array(['1', '2.0', 'Mohammed'], dtype='<U32')

In [43]:
#check type 
arr2.dtype.type

numpy.str_

In [11]:
#create 2D array with datatype : int16
dt = np.dtype(np.int16)
a = np.array([[1, 2], [3, 4]] , dtype=dt)
a
# a = np.array([[1, 2], [3, 4]], dtype=np.int16)
# a
# a = np.arange(12).reshape(4,3)
# a

array([[1, 2],
       [3, 4]], dtype=int16)

In [19]:
#check array dimension
a.ndim

2

In [15]:
# Get Shape
a.shape

(2, 2)

In [44]:
# Get  elements'Type
print(a[0].dtype,a[1].dtype)

int32 int32


In [16]:
# Get Size
a.itemsize

2

In [45]:
# Get number of elements
len(a)

2

In [17]:
# Get total size
a.size

4

### Accessing/Changing specific elements, rows, columns, etc

In [61]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [62]:
# get value: 13
a[1][5]

13

In [63]:
# Get second row
a[1]

array([ 8,  9, 10, 11, 12, 13, 14])

In [64]:
# Get 4th column
a[:, 3]

array([ 4, 11])

In [65]:
# Getting the elements that lies in first row and between 2nd and 6th column
a[0][2:5]

array([3, 4, 5])

In [67]:
#make the elements that lies in the second row and between first and 4th column to be 999
a[1][1:3]=999
a

array([[  1,   2,   3,   4,   5,   6,   7],
       [  8, 999, 999,  11,  12,  13,  14]])

### 3D example

#### create 3D array of 2 items (each item has 2 rows and  2 columns, that means shape(2*2*20

In [68]:
a_3d = np.arange(24).reshape((2, 3, 4))
print(a_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [70]:
# Get the second number, in the first matrix, in the 2nd item
a_3d[0][1][1]

5

### Initializing Different Types of Arrays

In [27]:
# create a zero matrix with 2 rows and 3 columns
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [71]:
# create  3D matrix with 4 rows and 2 columns and all elements have ones
np.ones((2,4,2), dtype='int32')

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [28]:
# create an 2*2 array and fill it with value of 99
b = np.ones((2,2), dtype='int32')
b*99
# b = np.arange(1,5).reshape(2,2)
# b.fill(99)
# b

array([[99, 99],
       [99, 99]])

In [72]:
# create 4*2 array with random decimal numbers
# c = np.random.rand(4,2)
# c
np.random.randint(1,10,(4,2))

array([[1, 9],
       [4, 6],
       [9, 5],
       [7, 5]])

In [30]:
# create 4*2 array with random integer numbers between values :-4 to 8
np.random.randint(-4,8,(4,2))

array([[ 7,  4],
       [ 1, -1],
       [-1,  6],
       [-1,  5]])

In [29]:
# create identity matrix 6*6
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

##### Statistics

In [31]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
#return mimimun value in the array
np.amin(stats)

1

In [33]:
#return the index of the maimum value in the array
np.amax(stats)

6

### Reorganizing Arrays

In [34]:
before = np.array([[1,2,3,4],[5,6,7,8]])

#reshape the array to 2 rows and 4 columns
before.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

In [36]:
# Vertically stacking vectors
np.vstack((v1, v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [37]:
# Horizontal  stack
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6, 7, 8])

##### Load Data from File using NumPy

In [38]:
file = np.loadtxt('data.txt', dtype = str)

OSError: data.txt not found.

##### Boolean Masking and Advanced Indexing

In [39]:
#return array of values between 50 and 100 only
np.arange(51,100)

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])